description: Helm chart for the HMCTS fees-register api
name: fees-register-api
home: https://github.com/hmcts/ccfr-fees-register-app
version: 0.0.1
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: jalal.deen@hmcts.net
