apiVersion: v2
appVersion: "2.0"
description: Helm chart for the HMCTS fees-register api
name: fees-register-api
home: https://github.com/hmcts/ccfr-fees-register-app
version: 0.4.9
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
dependencies:
  - name: java
    version: 5.3.0
    repository: 'oci://hmctspublic.azurecr.io/helm'
