apiVersion: v2
appVersion: "2.0"
description: Helm chart for the HMCTS fees-register api
name: fees-register-api
home: https://github.com/hmcts/ccfr-fees-register-app
version: 0.3.6
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
dependencies:
  - name: java
    version: 4.0.0
    repository: '@hmctspublic'
