apiVersion: v1
appVersion: "1.0"
description: Helm chart for the HMCTS fees-register api
name: fees-register-api
home: https://github.com/hmcts/ccfr-fees-register-app
version: 0.2.0
maintainers:
  - name: HMCTS Fees & Payments Dev Team
    email: ccpay@hmcts.net
