java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"
    SPRING_LIQUIBASE_ENABLED: true
    SPRING_CLOUD_PROPERTIESVOLUME_ENABLED: false
    ENABLE_FEE_LOADER: true
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/hmcts
    ISSUER_URI: https://idam-web-public.aat.platform.hmcts.net/o
    postgresql:
      postgresqlUsername: fees-register
      postgresqlPassword: fees-register
      postgresqlDatabase: fees-register


  postgresql:
    enabled: true

